# 在TestCase子类里验证相关的行为

在Python中编写测试的最经典办法是使用内置的unittest模块。

测试用例需要安排到TestCase的子类中。在这样的子类中，每个以test开头的方法都表示一项测试用例。如果test方法在运行过程中没有抛出任何异常（assert语句所触发的AssertionError也算异常），那么这项测试用例就是成功的，否则就是失败。其中一项测试用例失败，并不影响系统继续执行TestCase子类里的其他test方法。

```python
class TestJdMarket(unittest.TestCase):
    def test_filter_same_way_score_inshop_assign(self):
        obj = InshopStrategyBox()
        obj.context = {
            'is_multi_inshop_v2': False,
            'order_label_list': [1205],
            'pipeline_type': 2,
            'city_id': 1,
            'task_id': 1,
        }
        tmp_transporter_info = {
            "region_id_list": [],
            "pass_reason_dict": {},
            "is_rsv_nearby": False,
            "onhands_never_finish_order": {
                "292736798295712": {
                },
            },
        }
        obj.context.update({
            'supplier_group_id': 100009723,
            'order_label_list': [2085]
        })
        transporter_info = (112, tmp_transporter_info)
        result = obj.filter_same_way_score_inshop_assign(transporter_info)
        self.assertTrue(result)
```

TestCase类提供了一些辅助方法，可以在测试用例中做断言。例如，assertEqual方法可以确认两者是否相等，assertTrue可以确任Boolean表达式是否为True。

unittest最常见断言方法：

|         断言方法          |       检查条件       |
| :-----------------------: | :------------------: |
|     assertEqual(a, b)     |        a == b        |
|   assertNotEqual(a, b)    |        a != b        |
|       assertTrue(x)       |   bool(x) is True    |
|      assertFalse(x)       |   bool(x) is False   |
|      assertIs(a, b)       |        a is b        |
|     assertIsNot(a, b)     |      a is not b      |
|      assertIsNone(x)      |      x is None       |
|    assertIsNotNone(x)     |    x is not None     |
|      assertIn(a, b)       |        a in b        |
|     assertNotIn(a, b)     |      a not in b      |
|  assertlsInstance(a, b)   |   isinstance(a, b)   |
| assertNotIsInstance(a, b) | not isinstance(a, b) |



TestCase还提供了assertRaises这样一个辅助方法，它可以当作情境管理器用在with结构中，以验证该结构的主体部分是否会抛出应有的异常。

```python
from unittest import TestCase

class UtilsErrorTestCase(TestCase):
    def test_to_str_bad(self):
        with self.assertRaises(TypeError):
            list(2)
```



如果测试用例需要使用比较复杂的逻辑，那么可以把这些逻辑定义成辅助方法放到TestCase子类里。但是必须注意，这种方法的名称不能以test开头，否则系统就会把它们当成测试用例来执行。



TestCase类还提供了subTest辅助方法，可以让我们把相似的用例全都写在同一个test方法中，让它们成为这个用例中的子用例，这样的话，每个子用例所共用的那部分代码与逻辑只需要写一次就行。

```python
class NumbersTest(TestCase):
    def test_even(self):
        for i in range(0, 6):
            with self.subTest(i=i):
                self.assertEqual(i % 2, 0)
            
# One or more subtests failed
# Failed subtests list: (i=1), (i=3), (i=5)
```

某一行对应的子用例失败了，给出了一条有用的错误消息。这项子用例失败，并不影响方法中的其他子用例继续接受测试



如果项目比较复杂或者对测试的要求比较高，可以考虑用pytest这个开源软件包：

官方文档：https://pytest.org/

中文文档：https://www.osgeo.cn/pytest/contents.html#full-pytest-documentation

​                   https://learning-pytest.readthedocs.io/zh/latest/index.html

